### ISSUE TITLE
Great start on multi-image support, but...

### ISSUE THREAD

**Issue by ivannovak** [djpate/jTag#1]
I did run across a couple issues (or maybe things that aren't quite clear to me).

Now that we have multiple-image support, we also have the desire to save and relate tags to individual images and load those saved tags into the dom onload.

To me, it appears that there is no way, currently, to relate defaultTags to specific images when presented with multiple images (maybe there's another way to do this?).

I've taken a hack at attempting to add an image_id to options.save... which isn't a big deal as it's just adding a param to the function.  The part that I'm having a bit of a time working through is how to rework the options.defaultTags process to find existing images in the document and apply the proper defaultTags to the proper image.

I'd appreciate any insight you may be able to provide :)

Again, cheers on the work so far! Great job!

**Comment by djpate** [comment]
I dont really understand if your issue is with the JS or the php part.

If you just want to load differents defaultTag for multiple images check out my new demo7.html

If that doesn't help you let me know and I'll guide you for the php part...

**Comment by ivannovak** [comment]
My issue (previous to the update earlier today) was that I didn't realize that the tagging plugin needed to be applied to each individual image rather than all images in a matching group.

I was trying to do something like the following block and didn't quite get how one was supposed to apply defaultTags.

```
$('.tagme img').tag({
    showLabels: false,
        showTag: 'always',
        save: function(width,height,top_pos,left,label,the_tag){
            alert('I can save this tag ('+width+','+height+','+top_pos+','+left+','+label+')');
            /* once the ajax is done I need to get the ID here and then set it on the tag */
            the_tag.setId('someIdFromMyDb');
        },
        remove: function(id){
            alert('Here I can do some ajax to delete tag #'+id+' in my db');
        }
});
```

But now that the demo #7 illustrated that, in fact, each image needed to have it's own instance of the tagging plugin, that cleared it up completely.  I have it working smoothly now :)

Thanks!
